language: java
    
jdk:
  - oraclejdk11

services:
  - docker
  
addons:  
  chrome: stable 
  
notifications:
  email:
    - angular2guy@gmx.ch
  on_success: always
  on_failure: always

before_install:
  - nvm install 12.16
  - nvm use 12.16

      
script:
  mvn clean install -Ddocker=true
