language: java
    
jdk:
  - oraclejdk11

services:
  - docker
  
addons:  
  chrome: stable 
  
notifications:
  email:
    - angular2guy@gmx.ch
  on_success: always
  on_failure: always

before_install:
  - nvm install 8.9
  - nvm use 8.9
  - google-chrome-stable --headless --disable-gpu http://localhost &

      
script:
  mvn clean install -Ddocker=true
